### ISSUE TITLE
POST to /login with bad credentials should return 401 Unauthorized

### ISSUE THREAD

**Issue by dtcaciuc** [echlebek/erickson#2]
Currently it responds with 303 See Other. This happens here

https://github.com/echlebek/erickson/blob/master/server/auth.go#L82

According to w3 spec:

> If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials.

**Comment by echlebek** [comment]
I've changed the handler in this commit: https://github.com/echlebek/erickson/commit/424787896a0f3a63b5683eefb8f4ba0c3dee3283

Do you think this is correct now?

**Comment by dtcaciuc** [comment]
I pulled the new revision and now my test client correctly errors out on invalid password.

**Comment by dtcaciuc** [comment]
Actually, we should probably write a test case that verifies the valid/invalid login scenario.

**Comment by echlebek** [comment]
I modified the test client to check for 401 when bad credentials are supplied.
